#!/bin/bash

# allow running from anywhere
# when making an alias in .bashrc or /etc/environment: vpn="path/to/./run"

dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
cd "$(dirname "$(realpath "$0")")";
echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"

user_home=($HOME)
arg=$1

if [ ! "`whoami`" = "root" ]
then
    echo "\nPlease run script using sudo or as root."
    exit 1
fi

python vpnproxy_cli.py $user_home $arg

if [ "$?" -ne "0" ]; then
  echo "Python 2 not found. Attempting a run with python 3"
  python3 vpnproxy_cli.py $user_home $arg
fi

